import fs from 'node:fs/promises';
import path from 'node:path';

import {resolveModelProfile} from '../../../packages/policy-engine/src/index.js';

import {getRuntimePaths} from './paths.js';

function createId(prefix) {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

async function ensureStateDirs(paths) {
  await Promise.all([
    fs.mkdir(paths.taskDir, {recursive: true}),
    fs.mkdir(paths.runDir, {recursive: true}),
    fs.mkdir(paths.usageDir, {recursive: true}),
    fs.mkdir(paths.artifactDir, {recursive: true}),
    fs.mkdir(paths.reportDir, {recursive: true})
  ]);
}

async function writeJson(filePath, value) {
  await fs.mkdir(path.dirname(filePath), {recursive: true});
  await fs.writeFile(filePath, JSON.stringify(value, null, 2), 'utf8');
}

async function readJson(filePath) {
  const content = await fs.readFile(filePath, 'utf8');
  return JSON.parse(content);
}

export async function createTask(input = {}) {
  const runtime = getRuntimePaths();
  await ensureStateDirs(runtime);

  const task = {
    id: createId('task'),
    title: input.title || 'Scaffold task',
    risk: input.risk || 'medium',
    status: 'created',
    createdAt: new Date().toISOString(),
    storageMode: 'scaffold-filesystem',
    note: 'Synthetic state for runnable scaffold; replace with PostgreSQL-backed state in later phases.'
  };

  await writeJson(path.join(runtime.taskDir, `${task.id}.json`), task);
  return task;
}

export async function getTask(taskId) {
  const runtime = getRuntimePaths();
  return readJson(path.join(runtime.taskDir, `${taskId}.json`));
}

export async function startTask(taskId) {
  const runtime = getRuntimePaths();
  await ensureStateDirs(runtime);

  const taskPath = path.join(runtime.taskDir, `${taskId}.json`);
  const task = await readJson(taskPath);
  const startedAt = new Date().toISOString();
  const runId = createId('run');
  const modelProfile = resolveModelProfile({role: 'builder', risk: task.risk});

  const taskUpdate = {
    ...task,
    status: 'completed',
    updatedAt: startedAt
  };

  const artifactDir = path.join(runtime.artifactDir, runId);
  const artifactPath = path.join(artifactDir, 'summary.md');

  const run = {
    id: runId,
    taskId,
    status: 'completed',
    workerRole: 'builder',
    modelProfile,
    storageMode: 'scaffold-filesystem',
    steps: [
      {
        id: createId('step'),
        runId,
        stepName: 'queued',
        status: 'completed',
        details: {
          requestedProfile: modelProfile
        },
        createdAt: startedAt
      },
      {
        id: createId('step'),
        runId,
        stepName: 'running',
        status: 'completed',
        details: {
          workerRole: 'builder',
          requestedProfile: modelProfile
        },
        createdAt: startedAt
      },
      {
        id: createId('step'),
        runId,
        stepName: 'completed',
        status: 'completed',
        details: {
          provider: 'router9',
          modelProfile
        },
        createdAt: new Date().toISOString()
      }
    ],
    decisions: [
      {
        id: createId('decision'),
        runId,
        category: 'routing',
        subject: 'requested_profile',
        outcome: 'selected',
        evidence: {
          role: 'builder',
          risk: task.risk,
          requestedProfile: modelProfile,
          degraded: modelProfile === 'sofia-free-fallback'
        },
        createdAt: startedAt
      }
    ],
    artifacts: [
      {
        kind: 'report',
        uri: artifactPath
      }
    ],
    transitions: [
      {status: 'created', at: task.createdAt},
      {status: 'queued', at: startedAt},
      {status: 'running', at: startedAt},
      {status: 'completed', at: new Date().toISOString()}
    ]
  };

  await fs.mkdir(artifactDir, {recursive: true});
  await fs.writeFile(
    artifactPath,
    [
      '# Sofia Scaffold Artifact',
      '',
      `- Task: ${task.title}`,
      `- Risk: ${task.risk}`,
      `- Worker role: builder`,
      `- Model profile: ${modelProfile}`,
      '',
      'This artifact was generated by the scaffold runtime path.',
      'It demonstrates the task -> run -> artifact flow without claiming production-ready persistence.'
    ].join('\n'),
    'utf8'
  );

  const usage = {
    id: createId('usage'),
    runId,
    provider: 'router9',
    modelProfile,
    fallbackDepth: 0,
    tokensIn: 0,
    tokensOut: 0,
    note: 'Synthetic scaffold usage row'
  };

  await Promise.all([
    writeJson(taskPath, taskUpdate),
    writeJson(path.join(runtime.runDir, `${run.id}.json`), run),
    writeJson(path.join(runtime.usageDir, `${run.id}.json`), usage)
  ]);

  return {
    task: taskUpdate,
    run,
    artifact: {
      kind: 'report',
      uri: artifactPath
    },
    usage,
    steps: run.steps,
    decisions: run.decisions,
    artifacts: run.artifacts
  };
}

export async function getRun(runId) {
  const runtime = getRuntimePaths();
  return readJson(path.join(runtime.runDir, `${runId}.json`));
}
